STATE_MAPPING = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District Of Columbia",
    "FM": "Federated States Of Micronesia",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MH": "Marshall Islands",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "MP": "Northern Mariana Islands",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PW": "Palau",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VI": "Virgin Islands",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

STATE_POP = {'data': [{'ID State': '04000US30',
           'ID Year': 2018,
           'Population': 1062305,
           'Slug State': 'montana',
           'State': 'Montana',
           'Year': '2018'},
          {'ID State': '04000US01',
           'ID Year': 2018,
           'Population': 4887871,
           'Slug State': 'alabama',
           'State': 'Alabama',
           'Year': '2018'},
          {'ID State': '04000US04',
           'ID Year': 2018,
           'Population': 7171646,
           'Slug State': 'arizona',
           'State': 'Arizona',
           'Year': '2018'},
          {'ID State': '04000US05',
           'ID Year': 2018,
           'Population': 3013825,
           'Slug State': 'arkansas',
           'State': 'Arkansas',
           'Year': '2018'},
          {'ID State': '04000US06',
           'ID Year': 2018,
           'Population': 39557045,
           'Slug State': 'california',
           'State': 'California',
           'Year': '2018'},
          {'ID State': '04000US08',
           'ID Year': 2018,
           'Population': 5695564,
           'Slug State': 'colorado',
           'State': 'Colorado',
           'Year': '2018'},
          {'ID State': '04000US09',
           'ID Year': 2018,
           'Population': 3572665,
           'Slug State': 'connecticut',
           'State': 'Connecticut',
           'Year': '2018'},
          {'ID State': '04000US10',
           'ID Year': 2018,
           'Population': 967171,
           'Slug State': 'delaware',
           'State': 'Delaware',
           'Year': '2018'},
          {'ID State': '04000US11',
           'ID Year': 2018,
           'Population': 702455,
           'Slug State': 'district-of-columbia',
           'State': 'District of Columbia',
           'Year': '2018'},
          {'ID State': '04000US12',
           'ID Year': 2018,
           'Population': 21299325,
           'Slug State': 'florida',
           'State': 'Florida',
           'Year': '2018'},
          {'ID State': '04000US13',
           'ID Year': 2018,
           'Population': 10519475,
           'Slug State': 'georgia',
           'State': 'Georgia',
           'Year': '2018'},
          {'ID State': '04000US15',
           'ID Year': 2018,
           'Population': 1420491,
           'Slug State': 'hawaii',
           'State': 'Hawaii',
           'Year': '2018'},
          {'ID State': '04000US16',
           'ID Year': 2018,
           'Population': 1754208,
           'Slug State': 'idaho',
           'State': 'Idaho',
           'Year': '2018'},
          {'ID State': '04000US17',
           'ID Year': 2018,
           'Population': 12741080,
           'Slug State': 'illinois',
           'State': 'Illinois',
           'Year': '2018'},
          {'ID State': '04000US18',
           'ID Year': 2018,
           'Population': 6691878,
           'Slug State': 'indiana',
           'State': 'Indiana',
           'Year': '2018'},
          {'ID State': '04000US19',
           'ID Year': 2018,
           'Population': 3156145,
           'Slug State': 'iowa',
           'State': 'Iowa',
           'Year': '2018'},
          {'ID State': '04000US20',
           'ID Year': 2018,
           'Population': 2911510,
           'Slug State': 'kansas',
           'State': 'Kansas',
           'Year': '2018'},
          {'ID State': '04000US21',
           'ID Year': 2018,
           'Population': 4468402,
           'Slug State': 'kentucky',
           'State': 'Kentucky',
           'Year': '2018'},
          {'ID State': '04000US22',
           'ID Year': 2018,
           'Population': 4659978,
           'Slug State': 'louisiana',
           'State': 'Louisiana',
           'Year': '2018'},
          {'ID State': '04000US23',
           'ID Year': 2018,
           'Population': 1338404,
           'Slug State': 'maine',
           'State': 'Maine',
           'Year': '2018'},
          {'ID State': '04000US24',
           'ID Year': 2018,
           'Population': 6042718,
           'Slug State': 'maryland',
           'State': 'Maryland',
           'Year': '2018'},
          {'ID State': '04000US25',
           'ID Year': 2018,
           'Population': 6902149,
           'Slug State': 'massachusetts',
           'State': 'Massachusetts',
           'Year': '2018'},
          {'ID State': '04000US26',
           'ID Year': 2018,
           'Population': 9995915,
           'Slug State': 'michigan',
           'State': 'Michigan',
           'Year': '2018'},
          {'ID State': '04000US27',
           'ID Year': 2018,
           'Population': 5611179,
           'Slug State': 'minnesota',
           'State': 'Minnesota',
           'Year': '2018'},
          {'ID State': '04000US28',
           'ID Year': 2018,
           'Population': 2986530,
           'Slug State': 'mississippi',
           'State': 'Mississippi',
           'Year': '2018'},
          {'ID State': '04000US29',
           'ID Year': 2018,
           'Population': 6126452,
           'Slug State': 'missouri',
           'State': 'Missouri',
           'Year': '2018'},
          {'ID State': '04000US02',
           'ID Year': 2018,
           'Population': 737438,
           'Slug State': 'alaska',
           'State': 'Alaska',
           'Year': '2018'},
          {'ID State': '04000US31',
           'ID Year': 2018,
           'Population': 1929268,
           'Slug State': 'nebraska',
           'State': 'Nebraska',
           'Year': '2018'},
          {'ID State': '04000US32',
           'ID Year': 2018,
           'Population': 3034392,
           'Slug State': 'nevada',
           'State': 'Nevada',
           'Year': '2018'},
          {'ID State': '04000US33',
           'ID Year': 2018,
           'Population': 1356458,
           'Slug State': 'new-hampshire',
           'State': 'New Hampshire',
           'Year': '2018'},
          {'ID State': '04000US34',
           'ID Year': 2018,
           'Population': 8908520,
           'Slug State': 'new-jersey',
           'State': 'New Jersey',
           'Year': '2018'},
          {'ID State': '04000US35',
           'ID Year': 2018,
           'Population': 2095428,
           'Slug State': 'new-mexico',
           'State': 'New Mexico',
           'Year': '2018'},
          {'ID State': '04000US36',
           'ID Year': 2018,
           'Population': 19542209,
           'Slug State': 'new-york',
           'State': 'New York',
           'Year': '2018'},
          {'ID State': '04000US37',
           'ID Year': 2018,
           'Population': 10383620,
           'Slug State': 'north-carolina',
           'State': 'North Carolina',
           'Year': '2018'},
          {'ID State': '04000US38',
           'ID Year': 2018,
           'Population': 760077,
           'Slug State': 'north-dakota',
           'State': 'North Dakota',
           'Year': '2018'},
          {'ID State': '04000US39',
           'ID Year': 2018,
           'Population': 11689442,
           'Slug State': 'ohio',
           'State': 'Ohio',
           'Year': '2018'},
          {'ID State': '04000US40',
           'ID Year': 2018,
           'Population': 3943079,
           'Slug State': 'oklahoma',
           'State': 'Oklahoma',
           'Year': '2018'},
          {'ID State': '04000US41',
           'ID Year': 2018,
           'Population': 4190713,
           'Slug State': 'oregon',
           'State': 'Oregon',
           'Year': '2018'},
          {'ID State': '04000US42',
           'ID Year': 2018,
           'Population': 12807060,
           'Slug State': 'pennsylvania',
           'State': 'Pennsylvania',
           'Year': '2018'},
          {'ID State': '04000US44',
           'ID Year': 2018,
           'Population': 1057315,
           'Slug State': 'rhode-island',
           'State': 'Rhode Island',
           'Year': '2018'},
          {'ID State': '04000US45',
           'ID Year': 2018,
           'Population': 5084127,
           'Slug State': 'south-carolina',
           'State': 'South Carolina',
           'Year': '2018'},
          {'ID State': '04000US46',
           'ID Year': 2018,
           'Population': 882235,
           'Slug State': 'south-dakota',
           'State': 'South Dakota',
           'Year': '2018'},
          {'ID State': '04000US47',
           'ID Year': 2018,
           'Population': 6770010,
           'Slug State': 'tennessee',
           'State': 'Tennessee',
           'Year': '2018'},
          {'ID State': '04000US48',
           'ID Year': 2018,
           'Population': 28701845,
           'Slug State': 'texas',
           'State': 'Texas',
           'Year': '2018'},
          {'ID State': '04000US49',
           'ID Year': 2018,
           'Population': 3161105,
           'Slug State': 'utah',
           'State': 'Utah',
           'Year': '2018'},
          {'ID State': '04000US50',
           'ID Year': 2018,
           'Population': 626299,
           'Slug State': 'vermont',
           'State': 'Vermont',
           'Year': '2018'},
          {'ID State': '04000US51',
           'ID Year': 2018,
           'Population': 8517685,
           'Slug State': 'virginia',
           'State': 'Virginia',
           'Year': '2018'},
          {'ID State': '04000US53',
           'ID Year': 2018,
           'Population': 7535591,
           'Slug State': 'washington',
           'State': 'Washington',
           'Year': '2018'},
          {'ID State': '04000US54',
           'ID Year': 2018,
           'Population': 1805832,
           'Slug State': 'west-virginia',
           'State': 'West Virginia',
           'Year': '2018'},
          {'ID State': '04000US55',
           'ID Year': 2018,
           'Population': 5813568,
           'Slug State': 'wisconsin',
           'State': 'Wisconsin',
           'Year': '2018'},
          {'ID State': '04000US56',
           'ID Year': 2018,
           'Population': 577737,
           'Slug State': 'wyoming',
           'State': 'Wyoming',
           'Year': '2018'},
          {'ID State': '04000US72',
           'ID Year': 2018,
           'Population': 3195153,
           'Slug State': 'puerto-rico',
           'State': 'Puerto Rico',
           'Year': '2018'}],
 'source': [{'annotations': {'dataset_link': 'http://www.census.gov/programs-surveys/acs/',
                             'dataset_name': 'ACS 1-year Estimate',
                             'source_description': 'The American Community Survey (ACS) is conducted by the US Census and sent to a portion of the population every year.',
                             'source_name': 'Census Bureau',
                             'subtopic': 'Demographics',
                             'table_id': 'B01003',
                             'topic': 'Diversity'},
             'measures': ['Population'],
             'name': 'acs_yg_total_population_1',
             'substitutions': []}]}
